### ISSUE TITLE
Laggy drag and drop

### ISSUE THREAD

**Issue by stevenocchipinti** [stevenocchipinti/bleep#2]
Dragging items around in the config screen is very slow and looks like it's causing a lot of re-renders.
Will need to compare this to how the examples work on the dnd-kit site to compare implementations and how many renders occur.

**Comment by Anishali2** [comment]
i can do your job but first provide me the working application link so I can search for that 
``https://bleep-five.vercel.app/`` this link is not working

**Comment by stevenocchipinti** [comment]
https://bleep-timer.vercel.app/

**Comment by Anishali2** [comment]
So i just checked it out the issue of laggy drag and drop is causing because of 
```
 <Card
      transition="0.2s"
      transform={selected ? "scale(1.05)" : undefined}
      opacity={disabled ? 0.7 : 1}
      variant={selected ? "filled" : undefined}
      bg={selected ? "gray.600" : undefined}
      ref={setNodeRef}
      style={style}
      {...attributes}
      {...props}
    >...</Card>
 ``` 
this component that exist in `` /components/CardButton.tsx``
you have to use manual card component for this specific use case if you are okey with that I can do this job 
some packages have there custom reference for specific reference i might think that the ref of card component of charkra ui and sortable ref is colliding and causing this issue

**Comment by Anishali2** [comment]
I tried custom component and there is not a single pixel lag in it 
If you need then I'll do this but I think you are not working on this project any more so if you need help on this or any other project i can do

**Comment by stevenocchipinti** [comment]
That's nice of you to look into this, I wasn't expecting anyone to even find this repository 😅 thank you!

I don't have much time at the moment but if you'd like to submit a PR, I'll try to take a look.

Out of curiosity, are you using this app for yourself?

**Comment by Anishali2** [comment]
I've been using dnd-kit for a long time and i faced alot of issues and fix at the same time now 
i'm a bit expert in this library now i think there are more people like me who struggled alot at start so i think my time will help others 
Right now Im at office but will add a PR into your repo few hours later

Thanks!

**Comment by Anishali2** [comment]
> That's nice of you to look into this, I wasn't expecting anyone to even find this repository 😅 thank you!
> 
> I don't have much time at the moment but if you'd like to submit a PR, I'll try to take a look.
> 
> Out of curiosity, are you using this app for yourself?

no im not using im just finding some issues to be fixed on dnd-kit
PR is created now you can see that

**Comment by stevenocchipinti** [comment]
Wow, that's amazing! Thank you very much, I really appreciate it!

I'll take a look at that PR a bit later - I'm grateful for your help

**Comment by Anishali2** [comment]
call me anytime

**Comment by stevenocchipinti** [comment]
That's a great improvement!
Thank you once again :) 

I'm quite curious why you did this? Is it mainly to gain more experience for your own personal development?
Don't get me wrong, I'm really grateful, it's just I haven't ever had someone fix a bug for me like this before :)

**Comment by Anishali2** [comment]
@stevenocchipinti to be very clear. Im just tying to showcase my work to others and earn some good amout of income.

domain: https://app.tapday.com
email: hamza@gmail.com
pass: 123456789

This project is created by myself and it took me 1 year to build and i need to upscale my career and want to work on something that revolunize the future. I hope you understand my point.
Also I like sometimes to help someone else others not because I'm greedy of something just because that someone else remember me in good words 
Thanks for your appreciation it means a lot to me,

**Comment by stevenocchipinti** [comment]
That's great! That looks like a much more impressive project than my little exercise timer 😅 
I wish you all the best with your project - it's looking really good 👍 

Thanks again
